version: 0.2

phases:
  install:
    commands:
      - npm install
      - npm install -g mocha
      - npm install -g serverless
  build:
    commands:
      - npm run build
      - serverless deploy --stage $STAGE --branches $BRANCHES --repo $REPO --bucket $BUCKET