service: bitbucket-sync

frameworkVersion: ">=2.0.0 <3.0.0"

plugins:
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: eu-west-2
  timeout: 30
  iamRoleStatements:
    - Effect: Allow
      Action:
        - s3:GetObject
        - s3:PutObject
        - s3:PutObjectAcl
        - ssm:GetParameter
        - ssm:GetParameters
      Resource: "*"

functions:

  pullSourceCode:
    handler: src/lambda.repoToBucket
    memorySize: 128
    description: Clones a bitbucket repo into an S3 bucket 
    environment:
      BRANCHES: ${opt:branches}
      BUCKET: ${opt:bucket}
      REPO: ${opt:repo}

    events:
        - http:
            path: webhooks/bitbucket/
            method: post
            cors: true